food_delivery/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('register/', authapp.register, name='register'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
]

food_delivery/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    # path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
    path('editt/<int:pk>/', basketapp.editt, name='editt'),
    path('control/<int:pk>/', basketapp.control, name='control'),
    path('delete_all/<int:pk>/', basketapp.delete_all, name='delete_all'),
    path('ret/', basketapp.ret, name='ret'),
    path('order/', basketapp.order, name='order'),
    path('create_order/', basketapp.create_order, name='create_order'),
    path('order_list/', basketapp.order_list, name='order_list'),
    path('order_delete/<int:pk>/', basketapp.order_delete, name='order_delete')
]

food_delivery/food_delivery/urls.py
from django.contrib import admin
from django.urls import path

import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include




urlpatterns = [
    path('', mainapp.main, name='main'),
    path('catalog/', include('mainapp.urls', namespace='catalog')),
    path('admin/', admin.site.urls),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    # path('ordersapp/', include('ordersapp.urls', namespace='ordersapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_delivery/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import path

app_name="ordersapp"

urlpatterns = [
	path('create/', ordersapp.OrderList.as_view(), name='order_create')
	# path('delete/<int:pk>/', ordersapp.OrderDelete, name='order_delete')
]

food_delivery/ordersapp/models.py
from django.db import models

from django.conf import settings
from mainapp.models import Products


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    adress=models.TextField(verbose_name='адрес', blank=False)
    status = models.CharField(verbose_name='статус',
                              max_length=3,
                              choices=ORDER_STATUS_CHOICES,
                              default=FORMING)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return 'Текущий заказ: {}'.format(self.id)

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    # переопределяем метод, удаляющий объект
    def delete(self):
        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name="orderitems",
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                verbose_name='продукт',
                                on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество',
                                           default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

food_delivery/ordersapp/forms.py

from django import forms
from ordersapp.models import Order, OrderItem

class OrderForm(forms.ModelForm):
   class Meta:
       model = Order
       exclude = ('user',)

   def __init__(self, *args, **kwargs):
       super(OrderForm, self).__init__(*args, **kwargs)
       for field_name, field in self.fields.items():
           field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
   class Meta:
       model = OrderItem
       exclude = ()

   def __init__(self, *args, **kwargs):
       super(OrderItemForm, self).__init__(*args, **kwargs)
       for field_name, field in self.fields.items():
           field.widget.attrs['class'] = 'form-control'

food_delivery/ordersapp/views.py
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.db import transaction

from django.forms import inlineformset_factory

from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView

from basketapp.models import Basket
from ordersapp.models import Order, OrderItem
from ordersapp.forms import OrderItemForm


class OrderList(ListView):
   model = Order

   def get_queryset(self):
       return Order.objects.filter(user=self.request.user)

food_delivery/ordersapp/templates/ordersapp/create.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

</body>
</html>

food_delivery/ordersapp/templates/ordersapp/created.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}

food_delivery/ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}


{% block content %}
   <div class="h2 text-center head">
       Ваши заказы,
       {% if user.first_name %}
           {{ user.first_name|title}}
       {% else %}
           Пользователь
       {% endif %}
   </div>
   <table class="table orders_list">
       <thead>
         <tr>
           <th>ID</th>
           <th>Создан</th>
           <th>Обновлен</th>
           <th>Статус</th>
         </tr>
       </thead>
       <tbody>
           {% for item in object_list %}
               {% if item.is_active %}
               <tr>
                   <td class="td1 orders_list">{{ item.pk }}</td>
                   <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.get_status_display }}</td>
                   <td>
                       <a href="{% url 'ordersapp:order_read' item.pk %}">
                           посмотреть
                       </a>
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:order_update' item.pk %}">
                           редактировать
                         </a>
                       {% endif %}
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:order_delete' item.pk %}">
                             удалить
                         </a>
                       {% endif %}
                   </td>
               </tr>
               {% endif %}
           {% endfor %}
       </tbody>
   </table>
   <button class="btn btn-default btn-round">
       <a href="{% url 'main' %}">
           на главную
       </a>
   </button>
   <button class="btn btn-default btn-round">
       <a href="{% url 'ordersapp:order_create' %}">
           новый
       </a>
   </button>
{% endblock %}