food_delivery/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('register/', authapp.register, name='register'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
]

food_delivery/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    # path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
    path('editt/<int:pk>/', basketapp.editt, name='editt'),
    path('control/<int:pk>/', basketapp.control, name='control'),
    path('delete_all/<int:pk>/', basketapp.delete_all, name='delete_all'),
    path('ret/', basketapp.ret, name='ret'),
    path('order/', basketapp.order, name='order'),
    path('create_order/', basketapp.create_order, name='create_order'),
    path('order_list/', basketapp.order_list, name='order_list'),
    path('order_delete/<int:pk>/', basketapp.order_delete, name='order_delete')
]

food_delivery/food_delivery/urls.py
from django.contrib import admin
from django.urls import path

import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include




urlpatterns = [
    path('', mainapp.main, name='main'),
    path('catalog/', include('mainapp.urls', namespace='catalog')),
    path('admin/', admin.site.urls),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    # path('ordersapp/', include('ordersapp.urls', namespace='ordersapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_delivery/basketapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import Products, ProductCategory, Restaurant


class Basket(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='basket')
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    restauran = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)
    add_datetime = models.DateTimeField(verbose_name='время', auto_now_add=True)
    price = models.DecimalField(verbose_name='Цена', max_digits=20, decimal_places=2, default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    product_cost = property(get_product_cost)

    def get_total_quantity(self):
        items = Basket.objects.filter(user=self.user)
        totalquantity = sum(list(map(lambda x: x.quantity, items)))
        return totalquantity

    total_quantity = property(get_total_quantity)

    def _get_total_cost(self):
        items = Basket.objects.filter(user=self.user)
        totalcost = sum(list(map(lambda x: x.product_cost, items)))
        return totalcost

    total_cost = property(_get_total_cost)

    def get_items(user):
        items = Basket.objects.filter(user=user)
        return items

    items = property(get_items)


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address = models.TextField(verbose_name='Адрес доставки', max_length=300)
    phone = models.PositiveIntegerField(verbose_name='Телефон', default=0)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    def __str__(self):
        return 'Текущий заказ: {}'.format(self.id)

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))


class OrderItems(models.Model):
    order = models.ForeignKey(Order, related_name='orderitems', on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(self, pk):
        return OrderItem.objects.filter(pk=pk).first()

food_delivery/basketapp/forms.py
from django import forms
from django.forms import ModelForm
from basketapp.models import Order, OrderItems


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['address', 'phone']

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

food_delivery/basketapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from basketapp.models import Basket, Order, OrderItems
from mainapp.models import Products
from basketapp.forms import OrderForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.views.generic import ListView, CreateView, UpdateView, DeleteView


@login_required
def basket(request):
    title = 'Корзина'
    basket_items = Basket.objects.filter(user=request.user).order_by('product__category')

    content = {
        'title': title,
        'basket_items': basket_items,
    }

    return render(request, 'basketapp/basket.html', content)


@login_required
def basket_add(request, pk):
    product = get_object_or_404(Products, pk=pk)
    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(
            reverse('catalog:products_list', args=[product.restaurant__pk, product.category__pk]))
    basket = Basket.objects.filter(user=request.user, product=product).first()
    basket_user = Basket.objects.filter(user=request.user)
    restauran = product.restaurant
    if not basket:
        if not basket_user or product.restaurant == basket_user[0].restauran:
            basket = Basket(user=request.user, product=product, restauran=restauran)
        else:
            return HttpResponseRedirect(reverse('basket:control', args=[product.pk]))

    basket.quantity += 1
    basket.save()

    # return HttpResponseRedirect('http://127.0.0.1:8000/')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, pk):
    basket_record = get_object_or_404(Basket, pk=pk)

    # if request.method == 'POST':
    basket_record.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_edit(request, pk, quantity):
    if request.is_ajax():
        quantity = int(quantity)
        new_basket_item = Basket.objects.get(pk=int(pk))

        if quantity > 0:
            new_basket_item.quantity = quantity
            new_basket_item.save()
        else:
            new_basket_item.delete()

        basket_items = Basket.objects.filter(user=request.user).order_by('product__category')

        content = {'basket_items': basket_items}
        result = render_to_string('basketapp/includes/inc_basket_list.html', content)
        return JsonResponse({'result': result})


@login_required
def control(request, pk):
    basket = Basket.objects.filter(user=request.user).first()
    print('Привет', basket)
    product = Products.objects.get(pk=pk)
    content = {'product': product, 'basket': basket}
    return render(request, 'basketapp/control.html', content)


@login_required
def delete_all(request, pk):
    basket = Basket.objects.filter(user=request.user)
    print(basket)
    basket.delete()
    product = Products.objects.get(pk=pk)
    print('Привет', product.restaurant.pk, product.category.pk)
    return HttpResponseRedirect(reverse('catalog:products_list', args=[product.restaurant.pk, product.category.pk]))


@login_required
def ret(request):
    product = Basket.objects.filter(user=request.user).first()
    return HttpResponseRedirect(reverse('catalog:products_list', args=[product.restauran.pk, 0]))


@login_required
def editt(request, pk):
    if str(pk) in request.POST:
        quantity = request.POST.get(str(pk))
        # print('Привет', quantity)
        item = Basket.objects.get(pk=pk)
        if quantity == 0:
            item.delete()
        else:
            item.quantity = quantity
            item.save()
    title = 'Корзина'
    basket_items = Basket.objects.filter(user=request.user).order_by('product__category')

    content = {
        'title': title,
        'basket_items': basket_items,
    }

    return render(request, 'basketapp/basket.html', content)


@login_required
def order(request):
    title = 'Оформление заказа'
    if request.method == 'POST':
        print('Привет')
        order_form = OrderForm(request.POST)
        if order_form.is_valid():
            order_form.save()
            return HttpResponseRedirect(reverse('main'))
    else:

        order_form = OrderForm()
        user = request.user
        print(type(order_form))
    return render(request, 'basketapp/create_order.html', {'title': title, 'order_form': order_form, 'user': user})


def create_order(request):
    basket = Basket.objects.filter(user=request.user)
    a1 = Order()
    a1.user = request.user
    a1.address = '665838 Angarsk 22-2-82'
    a1.phone = 89148995893
    a1.save()
    for i in basket:
        a2 = OrderItems()
        a2.order = a1
        a2.product = i.product
        a2.quantity = i.quantity
        a2.save()

    # print(a1.orderitem)
    basket.delete()
    order_form = OrderForm()

    return render(request, 'basketapp/create_order.html', {"order_form": order_form})


def order_list(request):
    order = Order.objects.filter(user=request.user)

    title = 'просмотр заказов'

    content = {'title': title, 'order': order}

    return render(request, 'basketapp/order_list.html', content)



def order_delete(request, pk):
    order = get_object_or_404(Order, pk=pk)

    # if request.method == 'POST':
    order.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

food_delivery/basketapp/templates/basketapp/basket.html
{% extends 'basketapp/base.html' %}
{% load staticfiles %}

{% block content %}

<div class="basket_list">

{% include 'basketapp/includes/inc_basket_list.html' %}
</div>
{% if basket_items %}
<div class="basket_summary">
    В корзине {{ basket_items.0.total_quantity }} товаров общей стоимостью
    {{ basket_items.0.total_cost }} руб
</div>
{% endif %}


<button class="btn btn-round" style="text-align: center">
    <a class="text_button" href="{% url 'basket:order' %}">купить</a>

</button>
<button class="btn btn-round" style="text-align: center">
    <a class="text_button" href="{% url 'main' %}">на главную</a>
</button>
{% endblock %}

food_delivery/basketapp/templates/basketapp/control.html
{% extends 'basketapp/base.html' %}
{% load staticfiles %}

{% block content %}
<h4>Вы хотите добавит продукт другого ресторана, но заказ может формироваться только одним поставщиком.</h4>

<h4>Выхотите удалить продукты из ресторана {{ basket.restauran }} и начать заказывать из ресторана {{ product.restaurant }}</h4>

<button class="form-control">
    <a href="{% url 'basket:delete_all' product.pk %}" class="">ДА</a>
</button>
<button class="form-control">
    <a href="{% url 'basket:ret' %}" class="">НЕТ</a>
</button>

{% endblock %}

food_delivery/basketapp/templates/basketapp/create_order.html
{% extends 'basketapp/base.html' %}
{% load staticfiles %}


{% block content %}
<h3>оформление заказа пользователя {{user.username}}</h3>
<div class="">
    <form class="form-horizontal" action="{% url 'basket:create_order' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ order_form.as_p }}

        <input class="form-control" type="submit" value="сохранить">
    </form>

</div>
<button class="btn btn-round form-control last">
    <a href="{% url 'main' %}" class="">
        на главную
    </a>
</button>

{% endblock %}

food_delivery/basketapp/templates/basketapp/order_list.html
{% extends 'basketapp/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="">
    Ваши заказы,
    {% if user.first_name %}
    {{ user.first_name|title }}
    {% else %}
    Пользователь
    {% endif %}
</div>
<table class="">

    <tbody>
    {% for item in order %}

    <tr>
        <td>
            Заказа номер {{item.pk}}
        </td>

        <td>

            <a href="{% url 'basket:order_delete' item.pk %}">
                удалить
            </a>

        </td>
        <td>

            <a href="#">
                оплатить
            </a>

        </td>
    </tr>

    {% endfor %}
    </tbody>
</table>
<button class="btn btn-default btn-round">
    <a href="{% url 'main' %}">
        на главную
    </a>
</button>

{% endblock %}

food_delivery/basketapp/templates/basketapp/order_view.html
{% extends 'basketapp/base.html' %}
{% load staticfiles %}

{% block content %}

<div class="basket_list">

{% include 'basketapp/includes/inc_basket_list.html' %}
</div>
{% if basket_items %}
<div class="basket_summary">
    В корзине {{ basket_items.0.total_quantity }} товаров общей стоимостью
    {{ basket_items.0.total_cost }} руб
</div>
{% endif %}


<button class="btn btn-round" style="text-align: center">
    <a class="text_button" href="{% url 'basket:order' %}">купить</a>

</button>
<button class="btn btn-round" style="text-align: center">
    <a class="text_button" href="{% url 'main' %}">на главную</a>
</button>
{% endblock %}