food_delivery/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('register/', authapp.register, name='register'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
]

food_delivery/food_delivery/urls.py
from django.contrib import admin
from django.urls import path

import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include




urlpatterns = [
    path('', mainapp.main, name='main'),
    path('catalog/', include('mainapp.urls', namespace='catalog')),
    path('admin/', admin.site.urls),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    # path('ordersapp/', include('ordersapp.urls', namespace='ordersapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_delivery/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class ShopUser(AbstractUser):
    age = models.PositiveIntegerField(verbose_name='Возраст', default=18)
    is_active = models.BooleanField(verbose_name='активность', default=True)
    types = models.PositiveIntegerField(verbose_name='тип пользователя', default=1)

food_delivery/authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from authapp.models import ShopUser
import random
import hashlib


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'email', 'age')

    def __init__(self, *args, **kwargs):
        super(ShopUserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_txt = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды")

        return data

    # def save(self):
    #     user = super(ShopUserRegisterForm, self).save()
    #
    #     user.is_active = True
    #     # salt = hashlib.sha1(str(random.random()).encode('utf8')).hexdigest()[:6]
    #     # user.activation_key = hashlib.sha1((user.email + salt).encode('utf8')).hexdigest()
    #     user.save()
    #
    #     return user

class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'email', 'age', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

food_delivery/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import ShopUserLoginForm, ShopUserEditForm
from authapp.forms import ShopUserRegisterForm
from django.contrib import auth
from django.urls import reverse
from authapp.models import ShopUser


def login(request):
    title = 'Вход'

    login_form = ShopUserLoginForm(data=request.POST or None)

    if 'next' in request.POST.keys():
        next = request.POST['next']
    else:
        next = str(request.META.get('HTTP_REFERER'))
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:

            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('main'))

    content = {'title': title, 'login_form': login_form, 'next': next}

    # return redirect(return_path)

    return render(request, 'authapp/login.html', content)


def register(request):
    title = 'регистрация'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST)

        if register_form.is_valid():
            user = register_form.save()
            # if send_verify_mail(user):
            #     print('сообщение подтвердтверждения отправлено')
            return HttpResponseRedirect(reverse('main'))
            # else:
            #     print('ошибка отправки сообщения')
            #     return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm()

    content = {'title': title, 'register_form': register_form}

    return render(request, 'authapp/register.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))

def edit(request):
    title = 'редактирование'

    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, instance=request.user)


        if edit_form.is_valid():
            edit_form.save()

            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)


    content = {'title': title, 'edit_form': edit_form}

    return render(request, 'authapp/edit.html', content)

food_delivery/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    <link href="{% static 'assets/bootstrap/css/bootstrap.css' %}" rel="stylesheet">

    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/style_1.css' %}" rel="stylesheet">
    {% endblock %}
    {% block js %}

    {% endblock %}

</head>
<body>
<div class="container">
    <div class="login">
        <div class="text-login">Вход в систему</div>
        {% block content %}

        {% endblock %}
    </div>
</div>
</body>
</html>

food_delivery/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="form_user">
        <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ edit_form.as_p }}

            <input class="form-control" type="submit" value="сохранить">
        </form>

    </div>
    <button class="btn btn-round form-control last">
        <a href="{% url 'main' %}" class="">
            на главную
        </a>
    </button>

{% endblock %}

food_delivery/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div  class="login-form-position">
    <form action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}">
        {% endif %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Войти">
    </form>
    <button class="form-control">
        <a href="{% url 'auth:register' %}" class="">Зарегистрироваться</a>
    </button>
        <button class="form-control">
        <a href="{% url 'main' %}" class="">На главную страницу</a>
    </button>
    </div>
{% endblock %}

food_delivery/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
    <form class="" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
    	{% csrf_token %}
    	{{ register_form.as_p }}
    	<br>
    	<input type="submit" value="зарегестрироваться" class="">
    </form> 
{% endblock %}