food_delivery/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('register/', authapp.register, name='register'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
]

food_delivery/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    # path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
    path('editt/<int:pk>/', basketapp.editt, name='editt'),
    path('control/<int:pk>/', basketapp.control, name='control'),
    path('delete_all/<int:pk>/', basketapp.delete_all, name='delete_all'),
    path('ret/', basketapp.ret, name='ret'),
    path('order/', basketapp.order, name='order'),
    path('create_order/', basketapp.create_order, name='create_order'),
    path('order_list/', basketapp.order_list, name='order_list'),
    path('order_delete/<int:pk>/', basketapp.order_delete, name='order_delete')
]

food_delivery/food_delivery/urls.py
from django.contrib import admin
from django.urls import path

import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include




urlpatterns = [
    path('', mainapp.main, name='main'),
    path('catalog/', include('mainapp.urls', namespace='catalog')),
    path('admin/', admin.site.urls),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    # path('ordersapp/', include('ordersapp.urls', namespace='ordersapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_delivery/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns =[
    path('restaurants/<int:pk>/', mainapp.restaurants, name='restaurants'),
    path('products/<int:pk>/', mainapp.products, name='products'),
    path('products_list/<int:restaurant_pk>/<int:category_pk>/', mainapp.products_list, name='products_list'),
]

food_delivery/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='наименование категории', max_length=64, unique=True)
    image = models.ImageField(upload_to='category_images', blank=True)
    description = models.TextField(verbose_name='описание категории', blank=True)

    def __str__(self):
        return self.name


class Restaurant(models.Model):
    name = models.CharField(verbose_name='наименование ресторана', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание категории', blank=True)
    image = models.ImageField(upload_to='restaurant_images', blank=True)
    category = models.ManyToManyField(ProductCategory, through='RestaurantCategory')

    def __str__(self):
        return self.name


class RestaurantCategory(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)



class Products(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, null=True)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, null=True)
    name = models.CharField(verbose_name='наименование продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)

    def __str__(self):
        return "{0} ({1})".format(self.name, self.category.name)

food_delivery/mainapp/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
import random
from .models import Products, ProductCategory, Restaurant, RestaurantCategory
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, HttpRequest
from basketapp.models import Basket


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def main(request):
    title = 'Главная'
    categories = ProductCategory.objects.all()
    basket = get_basket(request.user)

    content = {'title': title,
               'categories': categories,
               'basket': basket,
               }
    return render(request, 'mainapp/index.html', content)


def restaurants(request, pk=None):
    if pk == 0:
        restaurant_list = Restaurant.objects.all()
        title = "Все рестораны"
    else:
        category = get_object_or_404(ProductCategory, pk=pk)
        restaurant_list = Restaurant.objects.filter(category__pk=pk)
        title = f'Рестораны, доставляющие {category.name}'
    basket = get_basket(request.user)
    content = {
        'title': title,
        'restaurant_list': restaurant_list,
        'basket': basket,
    }
    return render(request, 'mainapp/catalog.html', content)


def products(request, pk):
    links_menu = RestaurantCategory.objects.filter(restaurant=pk)
    restaurant = Restaurant.objects.get(pk=pk)
    products = Products.objects.filter(restaurant=pk)
    title = "Все продукты {}".format(restaurant)
    # else:
    #     category = get_object_or_404(ProductCategory, pk=pk)
    #     products = Products.objects.filter(restaurant__pk=pk)
    #
    #     title = f'Продукты ресторана: {category.name}'
    basket = get_basket(request.user)
    content = {
        'title': title,
        'links_menu': links_menu,
        'products': products,
        'restaurant': restaurant,
        'basket': basket,
    }

    return render(request, 'mainapp/products.html', content)


def products_list(request, restaurant_pk, category_pk):
    print('Привет', restaurant_pk, category_pk)
    links_menu = RestaurantCategory.objects.filter(restaurant=restaurant_pk)
    restaurant = Restaurant.objects.get(pk=restaurant_pk)
    if category_pk == 0:
        title = 'Все продукты в ресторане {}'.format(restaurant.name)
        products = Products.objects.filter(restaurant=restaurant_pk)
    else:
        category = ProductCategory.objects.get(pk=category_pk)
        products = Products.objects.filter(restaurant=restaurant_pk, category=category_pk)
        title = 'Продукты категории {} в ресторане {}'.format(category.name, restaurant.name)
    basket = get_basket(request.user)
    content = {
        'title': title,
        'links_menu': links_menu,
        'products': products,
        'restaurant': restaurant,
        'basket': basket,
    }
    return render(request, 'mainapp/products_list.html', content)

food_delivery/mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="content">
    <div class="restaurants">

        {% for restaurant in restaurant_list %}
        <div class="product-index">
            <img src="/media/{{ restaurant.image }}" alt="{{ restourant.short_desc }}" class="img-product-index">
            <a href="{% url 'catalog:products_list' restaurant.pk 0 %}" class="product-index-hover">{{ restaurant.name }}</a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

food_delivery/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block content %}

<div class="content">

    <div class="hot_products">
        <div class="hot_products_is">
            {% for category in categories %}
            <div class="product-index">
                <img src="/media/{{ category.image }}" alt="{{ product.short_desc }}" class="img-product-index">
                <a href="{% url 'catalog:restaurants' category.pk %}" class="product-index-hover">{{ category.name }}</a>
            </div>
            {% endfor %}
        </div>

    </div>

</div>
{% endblock %}

food_delivery/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block content %}


<div class="content">
    {% include 'mainapp/includes/inc_category_menu.html' %}
    <!--<h3 class="">{{category.name|title}}</h3>-->
    <div class="hot_products">
        <!--<h3 class="h3">Продукты</h3>-->
        <div class="hot_products_is">
            {% for product in products %}
            <a class="link_product_image_index" href="{% url 'basket:add' product.pk %}">
                <div class="restoran_of_category">

                    <img class="restoran_image" src="/media/{{ product.image }}"
                         style="width: 248px; height: 248px">
                    {{product.name}}
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

food_delivery/mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block content %}


<div class="content">
    <h3>{{title}}</h3>
    {% include 'mainapp/includes/inc_category_menu.html' %}
    <!--<h3 class="">{{category.name|title}}</h3>-->
    <div class="hot_products">
        <!--<h3 class="h3">Продукты</h3>-->
        <div class="hot_products_is">
            {% for product in products %}
            {% if user.is_authenticated %}
            <a class="link_product_image_index" href="{% url 'basket:add' product.pk %}">
                <div class="restoran_of_category">

                    <img class="restoran_image" src="/media/{{ product.image }}"
                         style="width: 248px; height: 248px">
                    {{product.name}}
                </div>
            </a>
            {% else %}
            <a class="link_product_image_index" href="{% url 'auth:login' %}">
                <div class="restoran_of_category">

                    <img class="restoran_image" src="/media/{{ product.image }}"
                         style="width: 248px; height: 248px">
                    {{product.name}}
                </div>

            </a>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

food_delivery/mainapp/templates/mainapp/products_restoran.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{'title': title, 'restoran': restoran, 'products': products,}
{% block content %}

<div class="content">
    <div class="hot_products">
        <h3 class="h3">Продукты</h3>
        <h3 class="h3">{{restoran.name}}</h3>

        <div class="hot_products_is">
            {% for product in products %}
            <a class="link_product_image_index" href="#">
                <div class="restoran_of_category">

                    <img class="restoran_image" src="/media/{{ product.image }}"
                         style="width: 248px; height: 248px">
                    {{product.name}}

                </div>
            </a>
            {% endfor %}
        </div>


    </div>
</div>


{% endblock %}

food_delivery/mainapp/templates/mainapp/restorans_list.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block content %}


<div class="content">
    {{restaurant.name}}
    {% include 'mainapp/includes/inc_category_menu.html' %}
    <!--<h3 class="">{{category.name|title}}</h3>-->
    <div class="hot_products">
        <!--<h3 class="h3">Продукты</h3>-->
        <div class="hot_products_is">
            {% for product in products %}
            <a class="link_product_image_index" href="{% url 'basket:add' product.pk %}">
                <div class="restoran_of_category">

                    <img class="restoran_image" src="/media/{{ product.image }}"
                         style="width: 248px; height: 248px">
                    {{product.name}}
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}